#!/bin/bash
#
#set -e

export NEXT_PUBLIC_DEPLOY_ENV=${DEPLOY_ENV}
export NEXT_PUBLIC_EDITION=${EDITION}
export NEXT_PUBLIC_API_PREFIX=${CONSOLE_API_URL}/console/api
export NEXT_PUBLIC_PUBLIC_API_PREFIX=${APP_API_URL}/api

export NEXT_PUBLIC_SENTRY_DSN=${SENTRY_DSN}
export NEXT_PUBLIC_SITE_ABOUT=${SITE_ABOUT}
export NEXT_PUBLIC_SERVER_URL=${SERVER_URL}

# 打印环境变量，用于调试
echo "DEPLOY_ENV: $NEXT_PUBLIC_DEPLOY_ENV"
echo "EDITION: $NEXT_PUBLIC_EDITION"
echo "API_PREFIX: $NEXT_PUBLIC_API_PREFIX"
echo "PUBLIC_API_PREFIX: $NEXT_PUBLIC_PUBLIC_API_PREFIX"
echo "SENTRY_DSN: $NEXT_PUBLIC_SENTRY_DSN"
echo "SITE_ABOUT: $NEXT_PUBLIC_SITE_ABOUT"
echo "SERVER_URL: $NEXT_PUBLIC_SERVER_URL"

pm2 start ./pm2.json --no-daemon
